# This is a basic workflow to help you get started with Actions

name: Test_VD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install xvfb
      - name: install xvfb
        run: sudo apt install -y xvfb

      # install dependencies
      - name: install dependencies
        run: pip install -r requirements.txt

      # run main.py
      - name: run main.py
        run: python main.py --url "http://www.aastocks.com/tc/stocks/quote/dynamic-chart.aspx?index=221000.FT"

      # # build docker image
      # - name: build docker image
      #   run: docker build . -t virtualdisplay:1.0 -f Dockerfile --rm

      # # run docker image
      # - name: run docker image
      #   run: docker run --name aastock -p 5000:5000 --rm virtualdisplay:1.0